# Baseline Configuration - Classification Only

# Model configuration
model:
  backbone_name: "resnet50"
  num_classes: 80
  pretrained: true
  freeze_backbone: false
  
  # Part extraction parameters (unused for baseline)
  num_parts: 6
  part_dim: 64
  use_adaptive_parts: false
  
  # Manifold parameters (unused for baseline)
  distance_metric: "log_euclidean"
  alignment_method: "bnn"
  shrinkage_alpha: null
  eps: 0.1e-4
  
  # Loss parameters (PAC-MCL disabled)
  gamma: 0.0  # Disable PAC-MCL loss
  lambda_pos_ce: 0.0  # Disable dual view
  margin: 0.2

# Data configuration
data:
  dataset_name: "cotton80"
  data_root: "./data"
  image_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

# Training configuration
training:
  epochs: 100
  batch_size: 64  # Larger batch for baseline
  num_workers: 4
  dual_view: false  # Single view training
  
  # Optimizer
  optimizer: "adamw"
  learning_rate: 0.1e-3
  weight_decay: 0.01
  
  # Learning rate scheduler
  scheduler:
    type: "cosine"
    params:
      T_max: 100
      eta_min: 0.1e-6

  # Early stopping
  early_stopping:
    patience: 15
    min_delta: 0.1e-4

  # Output
  output_dir: "./outputs/cotton80_resnet50_baseline"

# Experimental settings
experiment:
  name: "Baseline_Cotton80_ResNet50"
  description: "Baseline classification training on Cotton80 dataset"
  tags: ["baseline", "cotton80", "resnet50", "classification"]
  
  curriculum:
    enable: false
